-- Cargar items del checklist PAE (64 items)
-- Este archivo se ejecuta automáticamente durante la inicialización

-- Solo insertar si la tabla está vacía
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM checklist_items LIMIT 1) THEN
        INSERT INTO checklist_items (id, pregunta_texto, categoria_id, orden) VALUES
        (50, 'La cantidad de manipuladoras corresponde al numero de cupos asignados.', 1, 50),
        (51, 'En caso de no contar con el numero de manipuladoras corespondiente, se encuentra el documento de justificacion debidamente firmado, donde se especifique la razon por la que no se cumple con este personal y el acuerdo previamente establecido.', 1, 51),
        (52, 'No se evidencia presencia de animales en el establecimiento, especificamente en las areas destinadas a la fabricacion, procesamiento, preparacion, envase, almacenamiento y expendio.', 2, 52),
        (53, 'No se permite el almacenamiento de elementos, productos quimicos o peligrosos ajenos a las actividades propias realizadas en este.', 2, 53),
        (54, 'Los residuos solidos que se generan en el comedor escolar se encuentran ubicados de manera que no representen riesgo de contaminacion para el alimento, para los ambientes o superficies de potencial contacto con este.', 2, 54),
        (55, 'Los residuos solidos son removidos frecuentemente de las areas de produccion y estan ubicados de manera que se evite la generacion de malos olores, el refugio de animales y plagas y que ademas no contribuya al deterioro ambiental.', 2, 55),
        (56, 'Los recipientes utilizados para almacenamiento de residuos organicos e inorganicos, son a prueba de fugas, debidamente identificados, construidos de material impermeable, de facil limpieza y desinfeccion y de ser requerido estan provistos de tapa hermetica, dichos recipientes no pueden utilizarse para contener productos comestibles.', 2, 56),
        (115, 'Los equipos se encuentran instalados y ubicados segun la secuencia logica del proceso tecnologico, desde la recepcion de las materias primas y demas insumos, hasta el envasado y embalaje del producto terminado.', 3, 115),
        (116, 'La distancia entre los equipos y las paredes perimetrales, columnas u otros elementos de la edificacion, permite el funcionamiento de los equipos y facilita el acceso para la inspeccion, mantenimiento, limpieza y desinfeccion.', 3, 116),
        (57, 'El personal manipulador cuenta con certificacion medica, la cual especifique ser apto(a) para manipular alimentos.', 4, 57),
        (58, 'Se cuenta con un plan de capacitacion continuo y permanente para el personal manipulador de alimentos desde el momento de su contratacion y luego ser reforzado mediante charlas, cursos u otros medios efectivos de actualizacion. Dicho plan debe ser de por lo menos 10 horas anuales, sobre asuntos especificos relacionados al tema.', 4, 58),
        (59, 'El manipulador de alimentos se encuentra capacitado para comprender y manejar el control de los puntos del proceso que están bajo su responsabilidad y la importancia de su vigilancia o monitoreo; ademas, conoce los limites del punto del proceso y las acciones correctivas a tomar cuando existan desviaciones en dichos limites.', 4, 59),
        (60, 'El personal manipulador cuenta con una estricta limpieza e higiene personal y aplica buenas practicas higienicas en sus labores, de manera que se evite la contaminacion del alimento y de las superficies de contacto con este.', 5, 60),
        (61, 'El personal manipulador usa vestimenta de trabajo que cumpla los siguientes requisitos: De color claro que permita visualizar facilmente su limpieza; con cierres o cremalleras y/o broches en lugar de botones u otros accesorios que puedan caer en el alimento; sin bolsillos ubicados por encima de la cintura; usa calzado cerrado, de material resistente e impermeable y de tacon bajo. Cuando se utiliza delantal, este permanece atado al cuerpo en forma segura.', 5, 61),
        (62, 'El operador hace entrega de la dotacion completa al personal manipulador, conformada por (camisa, pantalon, cofia, tapaboca, delantal y calzado cerrado) en la cantidad establecida en el contrato vigente y de acuerdo con lo estipulado en el anexo tecnico. En caso que por usos y costumbres el personal manipulador no utilice la dotacion establecida, se cuenta con la certificacion firmada por el personal manipulador.', 5, 62),
        (63, 'El operador entrega en el periodo los siguientes elementos de higiene para cada manipulador (a): * 1 Jabon antibacterial inoloro en cantidad mayor o igual a 300 mL/cc * 1 Rollo de papel higienico', 5, 63),
        (64, 'El personal manipulador se lava y desinfecta las manos con agua y jabon antibacterial, antes de comenzar su trabajo, cada vez que salga y regrese al area asignada y despues de manipular cualquier material u objeto que pudiese representar un riesgo de contaminacion para el alimento.', 5, 64),
        (65, 'El personal manipulador cumple: * Mantiene el cabello recogido y cubierto totalmente mediante malla, gorro u otro medio efectivo y en caso de llevar barba, bigote o patillas usa cubiertas para estas. *No usa maquillaje.* utiliza tapabocas cubriendo nariz y boca mientras se manipula el alimento. *Mantiene las uñas cortas, limpias y sin esmalte. * No utiliza reloj, anillos, aretes, joyas u otros accesorios mientras realice sus labores. En caso de usar lentes, deben asegurarse a la cabeza mediante bandas, cadenas u otros medios ajustables.', 5, 65),
        (66, 'De ser necesario el uso de guantes, estos se mantienen limpios, sin roturas o desperfectos y son tratados con el mismo cuidado higienico de las manos sin proteccion. El material de los guantes, es apropiado para la operacion realizada y evitan la acumulacion de humedad y contaminacion en su interior para prevenir posibles afecciones cutaneas de los operarios. El uso de guantes no exime al operario de la obligacion de lavarse las manos.', 5, 66),
        (67, 'El personal manipulador no realiza actividades como: Beber o masticar cualquier objeto o producto, fumar o escupir en las areas de produccion o en cualquier otra zona donde exista riesgo de contaminacion del alimento.', 5, 67),
        (68, 'El personal manipulador no presenta afecciones de la piel o enfermedad infectocontagiosa.', 5, 68),
        (69, 'Los visitantes de los establecimientos cumplen estrictamente todas las practicas de higiene y portan la vestimenta y/o dotacion adecuada.', 5, 69),
        (70, 'La recepcion de materias primas se realiza en condiciones que eviten su contaminacion, alteracion y daños fisicos y estan debidamente identificadas de conformidad con la Resolucion 5109 de 2005 o las normas que la modifiquen, adicionen o sustituyan, y para el caso de los insumos, deben cumplir con las resoluciones 1506 de 2011 y/o la 683 de 2012, segun corresponda, o las normas que las modifiquen, adicionen o sustituyan.', 6, 70),
        (71, 'Las materias primas son sometidas a limpieza con agua potable u otro medio adecuado de ser requerido, se aplica la descontaminacion previa a su incorporacion en las etapas sucesivas del proceso.', 6, 71),
        (72, 'Las materias primas conservadas por congelacion que requieren ser descongeladas previo al uso, se descogelan a una velocidad controlada para evitar el desarrollo de microorganismos y no son recongeladas. Ademas, se manipulan de manera que se minimiza la contaminacion proveniente de otras fuentes.', 6, 72),
        (73, 'Las materias primas e insumos se almacenan en sitios exclusivos y adecuados que evitan su contaminacion y alteracion.', 6, 73),
        (74, 'Los alimentos que por su naturaleza permiten un rapido crecimiento de microorganismos indeseables, se mantienen en condiciones que eviten su proliferacion. - Alimentos a temperaturas de refrigeracion no mayores a 4°C/2ºC. - Alimento en estado congelado (-18 °C). - Alimento caliente a temperaturas mayores de 60°C (140°F).', 6, 74),
        (75, 'Las operaciones de fabricacion se realizan en forma secuencial y continua para que no se produzcan retrasos indebidos que permitan el crecimiento de microorganismos, contribuyan a otros tipos de deterioro o contaminacion del alimento. Cuando se requiera esperar entre una etapa del proceso y la siguiente, el alimento se mantiene protegido y en el caso de alimentos susceptibles al rapido crecimiento de microorganismos durante el tiempo de espera, se emplean temperaturas altas (> 60°C) o bajas no mayores de 4°C +/-2ºC segun sea el caso.', 7, 75),
        (76, 'Los procedimientos de manufactura, tales como, lavar, pelar, cortar, clasificar, desmenuzar, extraer, batir, secar, entre otros, se realizan de manera que se protegen los alimentos y las materias primas de la contaminacion.', 7, 76),
        (77, 'Durante las operaciones de fabricacion, almacenamiento y distribucion se toman medidas eficaces para evitar la contaminacion de los alimentos por contacto directo o indirecto con materias primas que se encuentren en las fases iniciales del proceso.', 8, 77),
        (78, 'Las operaciones de fabricacion se realizan en forma secuencial y continua para evitar el cruce de flujos de produccion.', 8, 78),
        (79, 'Todo equipo y utensilio que entra en contacto con materias primas o con material contaminado se limpia y se desinfecta cuidadosamente antes de ser utilizado nuevamente.', 8, 79),
        (80, 'En la recepcion de materias primas e insumos, se aplican los criterios de aceptacion, liberacion, retencion o rechazo.', 9, 80),
        (81, 'En la carpeta PAE se encuentra el Plan de Saneamiento establecido por la entidad territorial para la vigencia (programa de limpieza y desinfeccion, manejo de residuos, abastecimiento o suministro de agua y control integrado de plagas) con procedimientos escritos y registros de las actividades.', 10, 81),
        (82, 'El operador entrega los implementos de aseo minimos segun lo establecido anexos tecnicos (mayoritaria /indigena) y se realiza su reposicion en caso de que aplique.', 10, 82),
        (83, 'El operador entrega los insumos de aseo mensual para el comedor escolar, segun lo establecido en anexos tecnicos (mayoritaria /indigena) y se realiza su reposicion en caso que aplique.', 10, 83),
        (84, 'Se lleva control de primeras entradas y primeras salidas a diario, con el fin de garantizar la rotacion de los productos (formato kardex).', 11, 84),
        (85, 'El almacenamiento de materia prima e insumos, se realiza ordenadamente en pilas o estibas con separacion minima de 60 centimetros con respecto a las paredes perimetrales, y dispone de estibas o tarimas limpias y en buen estado, elevadas del piso por lo menos 15 centimetros de manera que permita la inspeccion, limpieza y fumigacion, si es el caso.', 11, 85),
        (86, 'En el lugar o espacio destinado al almacenamiento de materia prima e insumos, no se realizan actividades diferentes.', 11, 86),
        (87, 'Los plaguicidas, detergentes, desinfectantes y otras sustancias peligrosas, se encuentran debidamente rotuladas, incluida informacion sobre su modo de empleo y toxicidad, estos productos se almacenan en areas independientes con separacion fisica y su manipulacion solo es realizada por personal idoneo. Estas areas estan debidamente identificadas, organizadas, señalizadas y aireadas.', 11, 87),
        (88, 'El transporte de materias primas, insumos y producto terminado (CCT) se realiza en condiciones que impiden la contaminacion, la proliferacion de microorganismos y eviten su alteracion, incluidos los daños en el envase o embalaje segun sea el caso.', 12, 88),
        (89, 'Las materias primas que por su naturaleza requieran mantenerse refrigeradas o congeladas, son transportadas y distribuidas en condiciones que aseguran y garantizan su calidad  e inocuidad hasta su destino final. Este procedimiento es suceptible de verificacion mediante planiillas de registro de temperatura del vehiculo, durante el transporte, cargue o descargue del alimento.', 12, 89),
        (90, 'Los vehiculos de transporte de alimentos, estan diseñados en material sanitario en su interior y aquellos que poseen sistema de refrigeracion o congelacion, cuentan con indicador de temperatura y su funcionamiento garantiza la conservacion de los alimentos.', 12, 90),
        (91, 'Los contenedores o recipientes en los que se transportan los alimentos o materias primas, estan fabricados en materiales sanitarios que facilitan su correcta limpieza y desinfeccion.', 12, 91),
        (92, 'Se dispone de recipientes, canastillas o elementos, de material sanitario, que aislen el producto de toda posibilidad de contaminacion que pueda presentarse por contacto directo del alimento con el piso del vehiculo.', 12, 92),
        (93, 'No se transporta conjuntamente en un mismo vehiculo alimentos o materias primas con sustancias peligrosas u otras sustancias que por su naturaleza representen riesgo de contaminacion para el alimento o la materia prima.', 12, 93),
        (94, 'Los vehiculos en los que se transportan los alimentos o materias primas, llevan en su exterior de forma claramente visible la leyenda: Transporte de Alimentos.', 12, 94),
        (95, 'Los vehiculos destinados al transporte de alimentos y materias primas, cumplen dentro del territorio colombiano con los requisitos sanitarios que garantizan la adecuada proteccion y conservacion de los mismos.', 12, 95),
        (99, 'Se suministra el complemento en el horario establecido. En caso que se presente modificacion en el horario de servido, se encuentra definido de manera escrita mediante acta de reunion del CAE.', 13, 99),
        (100, 'El operador hace entrega de las materias primas e insumos, dentro del horario de la jornada escolar o por fuera del horario establecido, siempre y cuando no ponga en riesgo la calidad e inocuidad de las materias primas e insumos, ni la entrega oportuna del complemento alimentario.', 13, 100),
        (101, 'Se promueven los buenos habitos con los estudiantes como lo es el lavado de manos con jabon desinfectante antes del consumo de los alimentos.', 13, 101),
        (112, 'Se suministra el complemento en el horario establecido. En caso que se presente modificacion en el horario de servido, se encuentra definido de manera escrita mediante acta de reunion del CAE.', 13, 112),
        (113, 'El operador hace entrega de las materias primas e insumos, dentro del horario de la jornada escolar o por fuera del horario establecido, siempre y cuando no ponga en riesgo la calidad e inocuidad de las materias primas e insumos, ni la entrega oportuna del complemento alimentario.', 13, 113),
        (114, 'Se promueven los buenos habitos con los estudiantes como lo es el lavado de manos con jabon desinfectante antes del consumo de los alimentos.', 13, 114),
        (102, 'Existen avisos de señalizacion de areas ubicados en sitios estrategicos y en buen estado (verificar que sea del contrato vigente). Los avisos son: Area de recibo de alimentos - Area de almacenamiento - Area de preparacion - Area de distribucion - Comedor - Area de lavado - Avisos referentes a la necesidad de lavarse las manos luego de usar los servicios sanitarios.', 14, 102),
        (103, 'El operador entrega remision de materias primas e insumos (la cual debe contener como minimo: Nombre de la sede educativa, numero de cupos adjudicados y atendidos, la modalidad de atencion, los dias de atencion para los cuales se estan entregando los viveres, tipo de alimentos, unidad de medida, cantidad de entrega y espacio de observaciones), firmada por el personal manipulador de alimentos que recibe y existe copia de este documento en el comedor escolar.', 14, 103),
        (104, 'DEVOLUCIONES O FALTANTES: Se hace reposicion de materias primas o insumos faltantes, antes de la preparacion o entrega del alimento, de acuerdo con lo planeado en el ciclo de menu y el horario de servido estipulado, haciendo uso del formato establecido por la ETC, denominado "Reposicion y faltantes de alimentos", debidamente diligenciado y firmado por el personal manipulador de alimentos y un representante de la unidad de servicio, que certifique la entrega.', 14, 104),
        (105, 'En la carpeta PAE se encuentra el formato CARACTERISTICAS DE CALIDAD, COMPRA DE ALIMENTOS Y ELEMENTOS DE ASEO, donde se relacionan los alimentos e insumos entregados por el operador, debidamente diligenciado y legible.', 14, 105),
        (106, 'En la carpeta PAE se encuentra el documento de inventario de equipo y menaje debidamente diligenciado y firmado.', 14, 106),
        (107, 'El comedor escolar tiene publicado en un lugar visible la FICHA TECNICA de informacion del PAE, completamente diligenciada, incluidos los mecanismos que el operador y la ETC, tienen para atender las SPQR en el comedor escolar, de acuerdo con lo establecido por el MEN.', 14, 107),
        (108, 'Se cuenta con la carpeta del Programa de Alimentacion Escolar, organizada y debidamente identificada, con soportes de los programas implementados, informacion del personal manipulador (hoja de vida, certificado de BPM), gestiones realizadas y registros de la ejecucion del programa en el comedor escolar.', 14, 108),
        (109, 'En el comedor escolar está conformado el comité de alimentación escolar (CAE), y en la carpeta PAE reposa copia del acta de constitución CAE. Cuentan con actas de reunión del comité que evidencien su implementación.', 14, 109),
        (110, 'Se diligencia diariamente, sin interrupciones el formato registro y control de asistencia de titulares de derecho, beneficiarios del programa, sin tachones o enmendaduras.', 15, 110),
        (111, 'Verificacion de titulares atendiendos en el comedor Escolar donde la respuesta sea seleccionable, donde 1 cumple prcualmente 2 cumple 0 no cumple N/A no aplica y N/O no observado', 15, 111);
        
        RAISE NOTICE 'Checklist PAE: 64 items cargados exitosamente';
    ELSE
        RAISE NOTICE 'Checklist PAE: Items ya exist en, omitiendo carga';
    END IF;
END $$;

