name: frontend_visitas
description: "SMC VS - Sistema de Monitoreo y Control de Visitas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4   
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  file_picker: ^10.3.1
  intl: ^0.19.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.1
  path_provider_platform_interface: ^2.1.2
  connectivity_plus: ^6.1.4
  table_calendar: ^3.0.9
  geolocator: ^10.1.0
  # Notificaciones Push
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  permission_handler: ^11.1.0
  signature: ^5.4.0
  fl_chart: ^0.68.0
  url_launcher: ^6.3.1
  provider: ^6.1.1
  package_info_plus: ^8.0.0
  app_settings: ^5.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_cauca.png
    - assets/images/logo.png
    - assets/images/portada.png
    - assets/images/portada1.png
    - assets/images/logofup.png

# Configuración para el ícono de la aplicación
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/portada.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/portada.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/portada.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/portada.png"

